### ISSUE TITLE
fix: in row_count filter option is not applied

### ISSUE THREAD

**Issue by subhankarb** [waterdipai/datachecks#154]
**Describe the bug**
 Filter clause is not applying for row_count metric
 
 **Expected behavior**
```
  - name: in_search_staging_row_count
    metric_type: row_count
    resource: search_consumer_pgsql.country_product
    filters:
      where: "country_code = 'IND'"
```
this should filter results based on the where clause. But it does not applying
