### ISSUE TITLE
feat: Validity Metric String Length Max

### ISSUE THREAD

**Issue by subhankarb** [waterdipai/datachecks#174]
**Tell us about the problem you're trying to solve**

New validity metric for String Max Length

**Describe the solution you’d like**

We need to implement a new metric named `max_string_length`. The metric will generate the maximum value of the column's length.
The configuration example will be like below
```
metrics:
  - name: example_max_string_length
    metric_type: max_string_length
    resource: dcs_pgsql_db.dcs_iris.species
```
