### ISSUE TITLE
feat:

### ISSUE THREAD

**Issue by subhankarb** [waterdipai/datachecks#175]
**Tell us about the problem you're trying to solve**

New validity metric for String Min Length

**Describe the solution you’d like**

We need to implement a new metric named min_string_length. The metric will generate the minumum value of the column's length. This is only applicable to string columns.

The configuration example will be like below.

```
metrics:
  - name: example_min_string_length
    metric_type: min_string_length
    resource: dcs_pgsql_db.dcs_iris.species
```
