### ISSUE TITLE
[FEATURE] Table Segmentation

### ISSUE THREAD

**Issue by subhankarb** [waterdipai/datachecks#24]
**Tell us about the problem you're trying to solve**

As a user, I want to generate metrics for different table segments. 
For example, a table with one categorical column named C1 has values V1, V2, and V3. We want to get all the auto-metrics for the 3 sets of values.

**Describe the solution you’d like**

We need to provide configuration to the inspect class to generate segments.

```yaml
tables:
  table:
    segments:
      - name: n1
        where: c1 == v1
```
