### ISSUE TITLE
refactor: change input configuration from metric_type to type

### ISSUE THREAD

**Issue by subhankarb** [waterdipai/datachecks#43]
Currently, the configuration key for the type of the metric is `metric_type`. 

To make it uniform with the data_source name, we will rename it to `type`.

Current state:
```
metrics:
  - name: count_us_parts
    metric_type: document_count
    resource: search_datastore.product_data_us
```

Change it to:

```
metrics:
  - name: count_us_parts
    type: document_count
    resource: search_datastore.product_data_us
```
