### ISSUE TITLE
fix: Error handling while wrong datasource name reference in resource field

### ISSUE THREAD

**Issue by subhankarb** [waterdipai/datachecks#45]
**Describe the bug**

When the data source reference name is wrong in resource selector, it should capture the error and should provide a better error code.

**Expected behavior**
The run exists with proper error code and log message

**To Reproduce**
Add data sources in the configuration like below
```
data_sources:
  - name: search_datastore        # Data source name
    type: opensearch              # Data source type is OpenSearch
    connection:
      host: 127.0.0.1
      port: 9205
      username: !ENV ${OS_USER}   # Username to use for authentication ENV variables
      password: !ENV ${OS_PASS}
```
Add metrics like below
```
metrics:
  - name: count_us_parts
    metric_type: document_count
    resource: search_datastore1.product_data_us
```

**Screenshots**

![Image](https://github.com/waterdipai/datachecks/assets/2178361/78caf64a-e5f0-4ecf-9cdf-bf35ac5dc516)

**Logs and additional context**
If application, any other context, logs etc.here
