### ISSUE TITLE
fix: postgres datasource not able to connect to schema other than public

### ISSUE THREAD

**Issue by subhankarb** [waterdipai/datachecks#61]
**Describe the bug**
The configured schema is not propagating to the Postgres connection. The current status is

```python
 url = URL.create(
        drivername="postgresql",
        username=self.data_connection.get("username"),
        password=self.data_connection.get("password"),
        host=self.data_connection.get("host"),
        port=self.data_connection.get("port"),
        database=self.data_connection.get("database"),
    )
    engine = create_engine(url)
```
schema name should be part of engine creation.

**Expected behavior**
Postgres Datasource should table the schema name in the configuration. And the data source should connect to only that schema.

```yaml
  - name: search_staging_db       # Data source name
    type: postgres                # Data source type is Postgres
    connection:
      host: 127.0.0.1
      port: 5422
      username: !ENV ${DB2_USER}  # Username to use for authentication ENV variables
      password: !ENV ${DB2_PASS}  # Password to use for authentication ENV variables
      database: dc_db_2
      schema: custom_name
```

The code should accommodate the schema name

```python
schema = self.data_connection.get("schema")
#....
engine = create_engine(
    url,
    connect_args={'options': f'-csearch_path={schema}'},
    isolation_level="AUTOCOMMIT"
)
```
